version: '3.9'
services:
  app: 
    build: .
    environment:
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: postgres
      PGDATABASE: dev
      PGPORT: 5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4000:4000

  db:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5