version: '3.9'
services:
  app: 
    build: .
    environment:
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: postgres
      PGDATABASE: dev
      PGPORT: 5432
    depends_on:
      - db
    ports:
      - 4000:4000

  db:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
